import { promoSlider } from './modules/hero-slider';
import { toursSlider } from './modules/tours-slider';
import { getStarCount } from './modules/get-star-count';
import { trainersSlider } from './modules/trainers-slider';
import { reviewsSlider } from './modules/reviews-slider';
import { renderShadowTitle } from './modules/add-shadow';
import { advsSlider } from './modules/advantages-slider';
import { gallerySlider } from './modules/gallery-slider';
import { toggledMenu } from './modules/burger-menu';
import './modules/form-validate';

toggledMenu();
promoSlider();
toursSlider();
getStarCount();
trainersSlider();
reviewsSlider();
advsSlider();
gallerySlider();
renderShadowTitle();
