import { promoSlider } from './modules/hero-slider';
import { toursSlider } from './modules/tours-slider';
import { renderStars } from './modules/render-tour-stars';
import { trainersSlider } from './modules/trainers-slider';
import { reviewsSlider } from './modules/reviews-slider';
import { renderShadowTitle } from './modules/add-shadow-titles';
import { advsSlider } from './modules/advs-slider';
import { gallerySlider } from './modules/gallery-slider';
import { toggledMenu } from './modules/burger-menu';
import './modules/form-validate';

toggledMenu();
promoSlider();
toursSlider();
renderStars();
trainersSlider();
reviewsSlider();
advsSlider();
gallerySlider();
renderShadowTitle();
